version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - secrets:/mnt/secrets
    ports:
      - "80:80"
    command: ["python", "app.py"]

volumes:
  secrets:
    external: true
