version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: ["python", "app.py"]
    secrets:
      - DISCORD_BOT_TOKEN
      - OPENAI_API_KEY

secrets: 
  DISCORD_BOT_TOKEN:
    file: /mnt/secrets/discord_bot_token.txt
    # from environment variable (not recommended) 
  OPENAI_API_KEY:
    file: /mnt/secrets/openai_api_key.txt
